[build]
  publish = "dist/public"          # ✅ onde estão seus arquivos finais
  command = "npm run build"        # ✅ comando de build

[build.environment]
  NODE_VERSION = "18"              # ✅ especifica versão do Node no Netlify

[[redirects]]
  from = "/api/*"                  # ✅ serverless functions
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"                      # ✅ importante para SPA
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"  # ✅ onde suas funções estão (se tiver alguma)
